name: "wash: Build Component"
description: This action builds a component using wash
inputs:
  working-directory:
    description: "Directory with wasmcloud.toml"
    default: "."
    required: false
  build-args:
    description: "wash build arguments"
    default: "--skip-fetch"
    required: false
runs:
  using: "composite"
  steps:
    - name: Build Component
      shell: "bash"
      working-directory: "${{ inputs.working-directory }}"
      run: wash build ${{ inputs.build-args }}