---
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: wasmpay
  annotations:
    description: '🚀 wasmpay - The cross-border, cross-language payment solution powered by WebAssembly! 🌍💸 Send transactions seamlessly between banks, no matter the currency or language. Secure, fast, and extensible. Built for the future of finance! 🏦⚡'
    wasmcloud.dev/authors: Cosmonic team
    wasmcloud.dev/source-url: https://github.com/cosmonic-labs/wasmpay
spec:
  components:
    # WasmPay components
    - name: api-gateway
      type: component
      properties:
        image: file://./api-gateway/build/api-gateway_s.wasm
      traits:
        - type: spreadscaler
          properties:
            instances: 100
        - type: link
          properties:
            target:
              name: httpclient
            namespace: wasi
            package: http
            interfaces: [outgoing-handler]
        - type: link
          properties:
            target:
              name: transaction-manager
            namespace: wasmpay
            package: platform
            interfaces: [validation]
    - name: transaction-manager
      type: component
      properties:
        image: file://./transaction-manager/build/transaction_manager_s.wasm
      traits:
        - type: spreadscaler
          properties:
            instances: 100
        - type: link
          properties:
            name: wasmpay_platform
            target:
              name: wasmpay-validator
            namespace: wasmpay
            package: platform
            interfaces: [validation]
        - type: link
          properties:
            name: icamer
            target:
              name: icamer-validator
            namespace: wasmpay
            package: platform
            interfaces: [validation]
        - type: link
          properties:
            name: nordhaven
            target:
              name: nordhaven-validator
            namespace: wasmpay
            package: platform
            interfaces: [validation]
    - name: wasmpay-validator
      type: component
      properties:
        image: file://./wasmpay-validator/build/wasmpay-validator.composed_s.wasm
      traits:
        - type: spreadscaler
          properties:
            instances: 100

    # Bank "Untrusted" Validators
    - name: icamer-validator
      type: component
      properties:
        image: file://./icamer-validator/build/icamer_validator.composed_s.wasm
      traits:
        - type: spreadscaler
          properties:
            instances: 100
    - name: nordhaven-validator
      type: component
      properties:
        image: file://./nordhaven-validator/build/nordhaven-validator.composed_s.wasm
      traits:
        - type: spreadscaler
          properties:
            instances: 100

    # Providers
    - name: httpserver
      type: capability
      properties:
        image: wasmcloud+builtin://http-server
      traits:
        - type: link
          properties:
            target:
              name: api-gateway
            namespace: wasi
            package: http
            interfaces: [incoming-handler]
            source:
              config:
                - name: api-gateway-http
                  properties:
                    address: 0.0.0.0:8000
    - name: httpclient
      type: capability
      properties:
        image: ghcr.io/wasmcloud/http-client:0.13.0
