// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: proto/ledger/transfer/v1/transfer_service.proto

package transferv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_proto_ledger_transfer_v1_transfer_service_proto protoreflect.FileDescriptor

const file_proto_ledger_transfer_v1_transfer_service_proto_rawDesc = "" +
	"\n" +
	"/proto/ledger/transfer/v1/transfer_service.proto\x12\x18proto.ledger.transfer.v1\x1a'proto/ledger/transfer/v1/transfer.proto2v\n" +
	"\x0fTransferService\x12c\n" +
	"\bTransfer\x12).proto.ledger.transfer.v1.TransferRequest\x1a*.proto.ledger.transfer.v1.TransferResponse\"\x00B\xf8\x01\n" +
	"\x1ccom.proto.ledger.transfer.v1B\x14TransferServiceProtoP\x01Z?github.com/cosmonic-labs/wasmpay/ledger/internal/rpc/transferv1\xa2\x02\x03PLT\xaa\x02\x18Proto.Ledger.Transfer.V1\xca\x02\x18Proto\\Ledger\\Transfer\\V1\xe2\x02$Proto\\Ledger\\Transfer\\V1\\GPBMetadata\xea\x02\x1bProto::Ledger::Transfer::V1b\x06proto3"

var file_proto_ledger_transfer_v1_transfer_service_proto_goTypes = []any{
	(*TransferRequest)(nil),  // 0: proto.ledger.transfer.v1.TransferRequest
	(*TransferResponse)(nil), // 1: proto.ledger.transfer.v1.TransferResponse
}
var file_proto_ledger_transfer_v1_transfer_service_proto_depIdxs = []int32{
	0, // 0: proto.ledger.transfer.v1.TransferService.Transfer:input_type -> proto.ledger.transfer.v1.TransferRequest
	1, // 1: proto.ledger.transfer.v1.TransferService.Transfer:output_type -> proto.ledger.transfer.v1.TransferResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_ledger_transfer_v1_transfer_service_proto_init() }
func file_proto_ledger_transfer_v1_transfer_service_proto_init() {
	if File_proto_ledger_transfer_v1_transfer_service_proto != nil {
		return
	}
	file_proto_ledger_transfer_v1_transfer_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_ledger_transfer_v1_transfer_service_proto_rawDesc), len(file_proto_ledger_transfer_v1_transfer_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_ledger_transfer_v1_transfer_service_proto_goTypes,
		DependencyIndexes: file_proto_ledger_transfer_v1_transfer_service_proto_depIdxs,
	}.Build()
	File_proto_ledger_transfer_v1_transfer_service_proto = out.File
	file_proto_ledger_transfer_v1_transfer_service_proto_goTypes = nil
	file_proto_ledger_transfer_v1_transfer_service_proto_depIdxs = nil
}
