// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: api/transaction/v1/transaction.proto

package transactionv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TransactionRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// What account is sending money
	From string `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	// What account is money being sent to
	To string `protobuf:"bytes,2,opt,name=to,proto3" json:"to,omitempty"`
	// Currency-appropriate denomination
	Amount uint32 `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
	// Currency
	Currency      string `protobuf:"bytes,4,opt,name=currency,proto3" json:"currency,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransactionRequest) Reset() {
	*x = TransactionRequest{}
	mi := &file_api_transaction_v1_transaction_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionRequest) ProtoMessage() {}

func (x *TransactionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_transaction_v1_transaction_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionRequest.ProtoReflect.Descriptor instead.
func (*TransactionRequest) Descriptor() ([]byte, []int) {
	return file_api_transaction_v1_transaction_proto_rawDescGZIP(), []int{0}
}

func (x *TransactionRequest) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *TransactionRequest) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *TransactionRequest) GetAmount() uint32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *TransactionRequest) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

type TransactionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransactionResponse) Reset() {
	*x = TransactionResponse{}
	mi := &file_api_transaction_v1_transaction_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionResponse) ProtoMessage() {}

func (x *TransactionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_transaction_v1_transaction_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionResponse.ProtoReflect.Descriptor instead.
func (*TransactionResponse) Descriptor() ([]byte, []int) {
	return file_api_transaction_v1_transaction_proto_rawDescGZIP(), []int{1}
}

func (x *TransactionResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_api_transaction_v1_transaction_proto protoreflect.FileDescriptor

const file_api_transaction_v1_transaction_proto_rawDesc = "" +
	"\n" +
	"$api/transaction/v1/transaction.proto\x12\x12api.transaction.v1\"l\n" +
	"\x12TransactionRequest\x12\x12\n" +
	"\x04from\x18\x01 \x01(\tR\x04from\x12\x0e\n" +
	"\x02to\x18\x02 \x01(\tR\x02to\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\rR\x06amount\x12\x1a\n" +
	"\bcurrency\x18\x04 \x01(\tR\bcurrency\"/\n" +
	"\x13TransactionResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccessB\xd8\x01\n" +
	"\x16com.api.transaction.v1B\x10TransactionProtoP\x01ZBgithub.com/cosmonic-labs/wasmpay/ledger/internal/api/transactionv1\xa2\x02\x03ATX\xaa\x02\x12Api.Transaction.V1\xca\x02\x12Api\\Transaction\\V1\xe2\x02\x1eApi\\Transaction\\V1\\GPBMetadata\xea\x02\x14Api::Transaction::V1b\x06proto3"

var (
	file_api_transaction_v1_transaction_proto_rawDescOnce sync.Once
	file_api_transaction_v1_transaction_proto_rawDescData []byte
)

func file_api_transaction_v1_transaction_proto_rawDescGZIP() []byte {
	file_api_transaction_v1_transaction_proto_rawDescOnce.Do(func() {
		file_api_transaction_v1_transaction_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_transaction_v1_transaction_proto_rawDesc), len(file_api_transaction_v1_transaction_proto_rawDesc)))
	})
	return file_api_transaction_v1_transaction_proto_rawDescData
}

var file_api_transaction_v1_transaction_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_transaction_v1_transaction_proto_goTypes = []any{
	(*TransactionRequest)(nil),  // 0: api.transaction.v1.TransactionRequest
	(*TransactionResponse)(nil), // 1: api.transaction.v1.TransactionResponse
}
var file_api_transaction_v1_transaction_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_transaction_v1_transaction_proto_init() }
func file_api_transaction_v1_transaction_proto_init() {
	if File_api_transaction_v1_transaction_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_transaction_v1_transaction_proto_rawDesc), len(file_api_transaction_v1_transaction_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_transaction_v1_transaction_proto_goTypes,
		DependencyIndexes: file_api_transaction_v1_transaction_proto_depIdxs,
		MessageInfos:      file_api_transaction_v1_transaction_proto_msgTypes,
	}.Build()
	File_api_transaction_v1_transaction_proto = out.File
	file_api_transaction_v1_transaction_proto_goTypes = nil
	file_api_transaction_v1_transaction_proto_depIdxs = nil
}
