// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: api/ledger/v1/bank_service.proto

package ledgerv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetBankRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Value:
	//
	//	*GetBankRequest_Id
	//	*GetBankRequest_Code
	Value         isGetBankRequest_Value `protobuf_oneof:"value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBankRequest) Reset() {
	*x = GetBankRequest{}
	mi := &file_api_ledger_v1_bank_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBankRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBankRequest) ProtoMessage() {}

func (x *GetBankRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_ledger_v1_bank_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBankRequest.ProtoReflect.Descriptor instead.
func (*GetBankRequest) Descriptor() ([]byte, []int) {
	return file_api_ledger_v1_bank_service_proto_rawDescGZIP(), []int{0}
}

func (x *GetBankRequest) GetValue() isGetBankRequest_Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *GetBankRequest) GetId() string {
	if x != nil {
		if x, ok := x.Value.(*GetBankRequest_Id); ok {
			return x.Id
		}
	}
	return ""
}

func (x *GetBankRequest) GetCode() string {
	if x != nil {
		if x, ok := x.Value.(*GetBankRequest_Code); ok {
			return x.Code
		}
	}
	return ""
}

type isGetBankRequest_Value interface {
	isGetBankRequest_Value()
}

type GetBankRequest_Id struct {
	Id string `protobuf:"bytes,1,opt,name=id,proto3,oneof"`
}

type GetBankRequest_Code struct {
	Code string `protobuf:"bytes,2,opt,name=code,proto3,oneof"`
}

func (*GetBankRequest_Id) isGetBankRequest_Value() {}

func (*GetBankRequest_Code) isGetBankRequest_Value() {}

type GetBankResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bank          *Bank                  `protobuf:"bytes,1,opt,name=bank,proto3" json:"bank,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBankResponse) Reset() {
	*x = GetBankResponse{}
	mi := &file_api_ledger_v1_bank_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBankResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBankResponse) ProtoMessage() {}

func (x *GetBankResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_ledger_v1_bank_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBankResponse.ProtoReflect.Descriptor instead.
func (*GetBankResponse) Descriptor() ([]byte, []int) {
	return file_api_ledger_v1_bank_service_proto_rawDescGZIP(), []int{1}
}

func (x *GetBankResponse) GetBank() *Bank {
	if x != nil {
		return x.Bank
	}
	return nil
}

type ListBanksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBanksRequest) Reset() {
	*x = ListBanksRequest{}
	mi := &file_api_ledger_v1_bank_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBanksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBanksRequest) ProtoMessage() {}

func (x *ListBanksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_ledger_v1_bank_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBanksRequest.ProtoReflect.Descriptor instead.
func (*ListBanksRequest) Descriptor() ([]byte, []int) {
	return file_api_ledger_v1_bank_service_proto_rawDescGZIP(), []int{2}
}

type ListBanksResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Banks         []*Bank                `protobuf:"bytes,1,rep,name=banks,proto3" json:"banks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBanksResponse) Reset() {
	*x = ListBanksResponse{}
	mi := &file_api_ledger_v1_bank_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBanksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBanksResponse) ProtoMessage() {}

func (x *ListBanksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_ledger_v1_bank_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBanksResponse.ProtoReflect.Descriptor instead.
func (*ListBanksResponse) Descriptor() ([]byte, []int) {
	return file_api_ledger_v1_bank_service_proto_rawDescGZIP(), []int{3}
}

func (x *ListBanksResponse) GetBanks() []*Bank {
	if x != nil {
		return x.Banks
	}
	return nil
}

type CreateBankRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Country       string                 `protobuf:"bytes,3,opt,name=country,proto3" json:"country,omitempty"`
	Currency      string                 `protobuf:"bytes,4,opt,name=currency,proto3" json:"currency,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateBankRequest) Reset() {
	*x = CreateBankRequest{}
	mi := &file_api_ledger_v1_bank_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBankRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBankRequest) ProtoMessage() {}

func (x *CreateBankRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_ledger_v1_bank_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBankRequest.ProtoReflect.Descriptor instead.
func (*CreateBankRequest) Descriptor() ([]byte, []int) {
	return file_api_ledger_v1_bank_service_proto_rawDescGZIP(), []int{4}
}

func (x *CreateBankRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *CreateBankRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateBankRequest) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *CreateBankRequest) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

type CreateBankResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateBankResponse) Reset() {
	*x = CreateBankResponse{}
	mi := &file_api_ledger_v1_bank_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBankResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBankResponse) ProtoMessage() {}

func (x *CreateBankResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_ledger_v1_bank_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBankResponse.ProtoReflect.Descriptor instead.
func (*CreateBankResponse) Descriptor() ([]byte, []int) {
	return file_api_ledger_v1_bank_service_proto_rawDescGZIP(), []int{5}
}

func (x *CreateBankResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteBankRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteBankRequest) Reset() {
	*x = DeleteBankRequest{}
	mi := &file_api_ledger_v1_bank_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteBankRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteBankRequest) ProtoMessage() {}

func (x *DeleteBankRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_ledger_v1_bank_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteBankRequest.ProtoReflect.Descriptor instead.
func (*DeleteBankRequest) Descriptor() ([]byte, []int) {
	return file_api_ledger_v1_bank_service_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteBankRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type DeleteBankResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteBankResponse) Reset() {
	*x = DeleteBankResponse{}
	mi := &file_api_ledger_v1_bank_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteBankResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteBankResponse) ProtoMessage() {}

func (x *DeleteBankResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_ledger_v1_bank_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteBankResponse.ProtoReflect.Descriptor instead.
func (*DeleteBankResponse) Descriptor() ([]byte, []int) {
	return file_api_ledger_v1_bank_service_proto_rawDescGZIP(), []int{7}
}

var File_api_ledger_v1_bank_service_proto protoreflect.FileDescriptor

const file_api_ledger_v1_bank_service_proto_rawDesc = "" +
	"\n" +
	" api/ledger/v1/bank_service.proto\x12\rapi.ledger.v1\x1a\x18api/ledger/v1/bank.proto\"A\n" +
	"\x0eGetBankRequest\x12\x10\n" +
	"\x02id\x18\x01 \x01(\tH\x00R\x02id\x12\x14\n" +
	"\x04code\x18\x02 \x01(\tH\x00R\x04codeB\a\n" +
	"\x05value\":\n" +
	"\x0fGetBankResponse\x12'\n" +
	"\x04bank\x18\x01 \x01(\v2\x13.api.ledger.v1.BankR\x04bank\"\x12\n" +
	"\x10ListBanksRequest\">\n" +
	"\x11ListBanksResponse\x12)\n" +
	"\x05banks\x18\x01 \x03(\v2\x13.api.ledger.v1.BankR\x05banks\"q\n" +
	"\x11CreateBankRequest\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n" +
	"\acountry\x18\x03 \x01(\tR\acountry\x12\x1a\n" +
	"\bcurrency\x18\x04 \x01(\tR\bcurrency\"$\n" +
	"\x12CreateBankResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"'\n" +
	"\x11DeleteBankRequest\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\"\x14\n" +
	"\x12DeleteBankResponse2\xd5\x02\n" +
	"\vBankService\x12J\n" +
	"\aGetBank\x12\x1d.api.ledger.v1.GetBankRequest\x1a\x1e.api.ledger.v1.GetBankResponse\"\x00\x12P\n" +
	"\tListBanks\x12\x1f.api.ledger.v1.ListBanksRequest\x1a .api.ledger.v1.ListBanksResponse\"\x00\x12S\n" +
	"\n" +
	"CreateBank\x12 .api.ledger.v1.CreateBankRequest\x1a!.api.ledger.v1.CreateBankResponse\"\x00\x12S\n" +
	"\n" +
	"DeleteBank\x12 .api.ledger.v1.DeleteBankRequest\x1a!.api.ledger.v1.DeleteBankResponse\"\x00B\xba\x01\n" +
	"\x11com.api.ledger.v1B\x10BankServiceProtoP\x01Z=github.com/cosmonic-labs/wasmpay/ledger/internal/api/ledgerv1\xa2\x02\x03ALX\xaa\x02\rApi.Ledger.V1\xca\x02\rApi\\Ledger\\V1\xe2\x02\x19Api\\Ledger\\V1\\GPBMetadata\xea\x02\x0fApi::Ledger::V1b\x06proto3"

var (
	file_api_ledger_v1_bank_service_proto_rawDescOnce sync.Once
	file_api_ledger_v1_bank_service_proto_rawDescData []byte
)

func file_api_ledger_v1_bank_service_proto_rawDescGZIP() []byte {
	file_api_ledger_v1_bank_service_proto_rawDescOnce.Do(func() {
		file_api_ledger_v1_bank_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_ledger_v1_bank_service_proto_rawDesc), len(file_api_ledger_v1_bank_service_proto_rawDesc)))
	})
	return file_api_ledger_v1_bank_service_proto_rawDescData
}

var file_api_ledger_v1_bank_service_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_api_ledger_v1_bank_service_proto_goTypes = []any{
	(*GetBankRequest)(nil),     // 0: api.ledger.v1.GetBankRequest
	(*GetBankResponse)(nil),    // 1: api.ledger.v1.GetBankResponse
	(*ListBanksRequest)(nil),   // 2: api.ledger.v1.ListBanksRequest
	(*ListBanksResponse)(nil),  // 3: api.ledger.v1.ListBanksResponse
	(*CreateBankRequest)(nil),  // 4: api.ledger.v1.CreateBankRequest
	(*CreateBankResponse)(nil), // 5: api.ledger.v1.CreateBankResponse
	(*DeleteBankRequest)(nil),  // 6: api.ledger.v1.DeleteBankRequest
	(*DeleteBankResponse)(nil), // 7: api.ledger.v1.DeleteBankResponse
	(*Bank)(nil),               // 8: api.ledger.v1.Bank
}
var file_api_ledger_v1_bank_service_proto_depIdxs = []int32{
	8, // 0: api.ledger.v1.GetBankResponse.bank:type_name -> api.ledger.v1.Bank
	8, // 1: api.ledger.v1.ListBanksResponse.banks:type_name -> api.ledger.v1.Bank
	0, // 2: api.ledger.v1.BankService.GetBank:input_type -> api.ledger.v1.GetBankRequest
	2, // 3: api.ledger.v1.BankService.ListBanks:input_type -> api.ledger.v1.ListBanksRequest
	4, // 4: api.ledger.v1.BankService.CreateBank:input_type -> api.ledger.v1.CreateBankRequest
	6, // 5: api.ledger.v1.BankService.DeleteBank:input_type -> api.ledger.v1.DeleteBankRequest
	1, // 6: api.ledger.v1.BankService.GetBank:output_type -> api.ledger.v1.GetBankResponse
	3, // 7: api.ledger.v1.BankService.ListBanks:output_type -> api.ledger.v1.ListBanksResponse
	5, // 8: api.ledger.v1.BankService.CreateBank:output_type -> api.ledger.v1.CreateBankResponse
	7, // 9: api.ledger.v1.BankService.DeleteBank:output_type -> api.ledger.v1.DeleteBankResponse
	6, // [6:10] is the sub-list for method output_type
	2, // [2:6] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_api_ledger_v1_bank_service_proto_init() }
func file_api_ledger_v1_bank_service_proto_init() {
	if File_api_ledger_v1_bank_service_proto != nil {
		return
	}
	file_api_ledger_v1_bank_proto_init()
	file_api_ledger_v1_bank_service_proto_msgTypes[0].OneofWrappers = []any{
		(*GetBankRequest_Id)(nil),
		(*GetBankRequest_Code)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_ledger_v1_bank_service_proto_rawDesc), len(file_api_ledger_v1_bank_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_ledger_v1_bank_service_proto_goTypes,
		DependencyIndexes: file_api_ledger_v1_bank_service_proto_depIdxs,
		MessageInfos:      file_api_ledger_v1_bank_service_proto_msgTypes,
	}.Build()
	File_api_ledger_v1_bank_service_proto = out.File
	file_api_ledger_v1_bank_service_proto_goTypes = nil
	file_api_ledger_v1_bank_service_proto_depIdxs = nil
}
