// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: api/ledger/v1/bank.proto

package ledgerv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Bank struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Code          string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Country       string                 `protobuf:"bytes,4,opt,name=country,proto3" json:"country,omitempty"`
	Currency      string                 `protobuf:"bytes,5,opt,name=currency,proto3" json:"currency,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Bank) Reset() {
	*x = Bank{}
	mi := &file_api_ledger_v1_bank_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Bank) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bank) ProtoMessage() {}

func (x *Bank) ProtoReflect() protoreflect.Message {
	mi := &file_api_ledger_v1_bank_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bank.ProtoReflect.Descriptor instead.
func (*Bank) Descriptor() ([]byte, []int) {
	return file_api_ledger_v1_bank_proto_rawDescGZIP(), []int{0}
}

func (x *Bank) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Bank) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *Bank) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Bank) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *Bank) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

var File_api_ledger_v1_bank_proto protoreflect.FileDescriptor

const file_api_ledger_v1_bank_proto_rawDesc = "" +
	"\n" +
	"\x18api/ledger/v1/bank.proto\x12\rapi.ledger.v1\"t\n" +
	"\x04Bank\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x18\n" +
	"\acountry\x18\x04 \x01(\tR\acountry\x12\x1a\n" +
	"\bcurrency\x18\x05 \x01(\tR\bcurrencyB\xb3\x01\n" +
	"\x11com.api.ledger.v1B\tBankProtoP\x01Z=github.com/cosmonic-labs/wasmpay/ledger/internal/api/ledgerv1\xa2\x02\x03ALX\xaa\x02\rApi.Ledger.V1\xca\x02\rApi\\Ledger\\V1\xe2\x02\x19Api\\Ledger\\V1\\GPBMetadata\xea\x02\x0fApi::Ledger::V1b\x06proto3"

var (
	file_api_ledger_v1_bank_proto_rawDescOnce sync.Once
	file_api_ledger_v1_bank_proto_rawDescData []byte
)

func file_api_ledger_v1_bank_proto_rawDescGZIP() []byte {
	file_api_ledger_v1_bank_proto_rawDescOnce.Do(func() {
		file_api_ledger_v1_bank_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_ledger_v1_bank_proto_rawDesc), len(file_api_ledger_v1_bank_proto_rawDesc)))
	})
	return file_api_ledger_v1_bank_proto_rawDescData
}

var file_api_ledger_v1_bank_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_api_ledger_v1_bank_proto_goTypes = []any{
	(*Bank)(nil), // 0: api.ledger.v1.Bank
}
var file_api_ledger_v1_bank_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_ledger_v1_bank_proto_init() }
func file_api_ledger_v1_bank_proto_init() {
	if File_api_ledger_v1_bank_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_ledger_v1_bank_proto_rawDesc), len(file_api_ledger_v1_bank_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_ledger_v1_bank_proto_goTypes,
		DependencyIndexes: file_api_ledger_v1_bank_proto_depIdxs,
		MessageInfos:      file_api_ledger_v1_bank_proto_msgTypes,
	}.Build()
	File_api_ledger_v1_bank_proto = out.File
	file_api_ledger_v1_bank_proto_goTypes = nil
	file_api_ledger_v1_bank_proto_depIdxs = nil
}
