// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: api/ledger/v1/transaction_service.proto

package ledgerv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StoreTransactionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Origin        string                 `protobuf:"bytes,1,opt,name=origin,proto3" json:"origin,omitempty"`
	Destination   string                 `protobuf:"bytes,2,opt,name=destination,proto3" json:"destination,omitempty"`
	Amount        uint64                 `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
	Currency      string                 `protobuf:"bytes,4,opt,name=currency,proto3" json:"currency,omitempty"`
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	Reason        string                 `protobuf:"bytes,6,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StoreTransactionRequest) Reset() {
	*x = StoreTransactionRequest{}
	mi := &file_api_ledger_v1_transaction_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoreTransactionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreTransactionRequest) ProtoMessage() {}

func (x *StoreTransactionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_ledger_v1_transaction_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreTransactionRequest.ProtoReflect.Descriptor instead.
func (*StoreTransactionRequest) Descriptor() ([]byte, []int) {
	return file_api_ledger_v1_transaction_service_proto_rawDescGZIP(), []int{0}
}

func (x *StoreTransactionRequest) GetOrigin() string {
	if x != nil {
		return x.Origin
	}
	return ""
}

func (x *StoreTransactionRequest) GetDestination() string {
	if x != nil {
		return x.Destination
	}
	return ""
}

func (x *StoreTransactionRequest) GetAmount() uint64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *StoreTransactionRequest) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *StoreTransactionRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *StoreTransactionRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type StoreTransactionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StoreTransactionResponse) Reset() {
	*x = StoreTransactionResponse{}
	mi := &file_api_ledger_v1_transaction_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoreTransactionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreTransactionResponse) ProtoMessage() {}

func (x *StoreTransactionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_ledger_v1_transaction_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreTransactionResponse.ProtoReflect.Descriptor instead.
func (*StoreTransactionResponse) Descriptor() ([]byte, []int) {
	return file_api_ledger_v1_transaction_service_proto_rawDescGZIP(), []int{1}
}

func (x *StoreTransactionResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ListTransactionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTransactionsRequest) Reset() {
	*x = ListTransactionsRequest{}
	mi := &file_api_ledger_v1_transaction_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTransactionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTransactionsRequest) ProtoMessage() {}

func (x *ListTransactionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_ledger_v1_transaction_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTransactionsRequest.ProtoReflect.Descriptor instead.
func (*ListTransactionsRequest) Descriptor() ([]byte, []int) {
	return file_api_ledger_v1_transaction_service_proto_rawDescGZIP(), []int{2}
}

type ListTransactionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Transactions  []*Transaction         `protobuf:"bytes,1,rep,name=transactions,proto3" json:"transactions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTransactionsResponse) Reset() {
	*x = ListTransactionsResponse{}
	mi := &file_api_ledger_v1_transaction_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTransactionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTransactionsResponse) ProtoMessage() {}

func (x *ListTransactionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_ledger_v1_transaction_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTransactionsResponse.ProtoReflect.Descriptor instead.
func (*ListTransactionsResponse) Descriptor() ([]byte, []int) {
	return file_api_ledger_v1_transaction_service_proto_rawDescGZIP(), []int{3}
}

func (x *ListTransactionsResponse) GetTransactions() []*Transaction {
	if x != nil {
		return x.Transactions
	}
	return nil
}

var File_api_ledger_v1_transaction_service_proto protoreflect.FileDescriptor

const file_api_ledger_v1_transaction_service_proto_rawDesc = "" +
	"\n" +
	"'api/ledger/v1/transaction_service.proto\x12\rapi.ledger.v1\x1a\x1fapi/ledger/v1/transaction.proto\"\xb7\x01\n" +
	"\x17StoreTransactionRequest\x12\x16\n" +
	"\x06origin\x18\x01 \x01(\tR\x06origin\x12 \n" +
	"\vdestination\x18\x02 \x01(\tR\vdestination\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x04R\x06amount\x12\x1a\n" +
	"\bcurrency\x18\x04 \x01(\tR\bcurrency\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12\x16\n" +
	"\x06reason\x18\x06 \x01(\tR\x06reason\"*\n" +
	"\x18StoreTransactionResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x19\n" +
	"\x17ListTransactionsRequest\"Z\n" +
	"\x18ListTransactionsResponse\x12>\n" +
	"\ftransactions\x18\x01 \x03(\v2\x1a.api.ledger.v1.TransactionR\ftransactions2\xe2\x01\n" +
	"\x12TransactionService\x12e\n" +
	"\x10StoreTransaction\x12&.api.ledger.v1.StoreTransactionRequest\x1a'.api.ledger.v1.StoreTransactionResponse\"\x00\x12e\n" +
	"\x10ListTransactions\x12&.api.ledger.v1.ListTransactionsRequest\x1a'.api.ledger.v1.ListTransactionsResponse\"\x00B\xc1\x01\n" +
	"\x11com.api.ledger.v1B\x17TransactionServiceProtoP\x01Z=github.com/cosmonic-labs/wasmpay/ledger/internal/api/ledgerv1\xa2\x02\x03ALX\xaa\x02\rApi.Ledger.V1\xca\x02\rApi\\Ledger\\V1\xe2\x02\x19Api\\Ledger\\V1\\GPBMetadata\xea\x02\x0fApi::Ledger::V1b\x06proto3"

var (
	file_api_ledger_v1_transaction_service_proto_rawDescOnce sync.Once
	file_api_ledger_v1_transaction_service_proto_rawDescData []byte
)

func file_api_ledger_v1_transaction_service_proto_rawDescGZIP() []byte {
	file_api_ledger_v1_transaction_service_proto_rawDescOnce.Do(func() {
		file_api_ledger_v1_transaction_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_ledger_v1_transaction_service_proto_rawDesc), len(file_api_ledger_v1_transaction_service_proto_rawDesc)))
	})
	return file_api_ledger_v1_transaction_service_proto_rawDescData
}

var file_api_ledger_v1_transaction_service_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_api_ledger_v1_transaction_service_proto_goTypes = []any{
	(*StoreTransactionRequest)(nil),  // 0: api.ledger.v1.StoreTransactionRequest
	(*StoreTransactionResponse)(nil), // 1: api.ledger.v1.StoreTransactionResponse
	(*ListTransactionsRequest)(nil),  // 2: api.ledger.v1.ListTransactionsRequest
	(*ListTransactionsResponse)(nil), // 3: api.ledger.v1.ListTransactionsResponse
	(*Transaction)(nil),              // 4: api.ledger.v1.Transaction
}
var file_api_ledger_v1_transaction_service_proto_depIdxs = []int32{
	4, // 0: api.ledger.v1.ListTransactionsResponse.transactions:type_name -> api.ledger.v1.Transaction
	0, // 1: api.ledger.v1.TransactionService.StoreTransaction:input_type -> api.ledger.v1.StoreTransactionRequest
	2, // 2: api.ledger.v1.TransactionService.ListTransactions:input_type -> api.ledger.v1.ListTransactionsRequest
	1, // 3: api.ledger.v1.TransactionService.StoreTransaction:output_type -> api.ledger.v1.StoreTransactionResponse
	3, // 4: api.ledger.v1.TransactionService.ListTransactions:output_type -> api.ledger.v1.ListTransactionsResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_ledger_v1_transaction_service_proto_init() }
func file_api_ledger_v1_transaction_service_proto_init() {
	if File_api_ledger_v1_transaction_service_proto != nil {
		return
	}
	file_api_ledger_v1_transaction_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_ledger_v1_transaction_service_proto_rawDesc), len(file_api_ledger_v1_transaction_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_ledger_v1_transaction_service_proto_goTypes,
		DependencyIndexes: file_api_ledger_v1_transaction_service_proto_depIdxs,
		MessageInfos:      file_api_ledger_v1_transaction_service_proto_msgTypes,
	}.Build()
	File_api_ledger_v1_transaction_service_proto = out.File
	file_api_ledger_v1_transaction_service_proto_goTypes = nil
	file_api_ledger_v1_transaction_service_proto_depIdxs = nil
}
