// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: api/transfer/v1/transfer_service.proto

package transferv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_api_transfer_v1_transfer_service_proto protoreflect.FileDescriptor

const file_api_transfer_v1_transfer_service_proto_rawDesc = "" +
	"\n" +
	"&api/transfer/v1/transfer_service.proto\x12\x0fapi.transfer.v1\x1a\x1eapi/transfer/v1/transfer.proto2d\n" +
	"\x0fTransferService\x12Q\n" +
	"\bTransfer\x12 .api.transfer.v1.TransferRequest\x1a!.api.transfer.v1.TransferResponse\"\x00B\xca\x01\n" +
	"\x13com.api.transfer.v1B\x14TransferServiceProtoP\x01Z?github.com/cosmonic-labs/wasmpay/ledger/internal/api/transferv1\xa2\x02\x03ATX\xaa\x02\x0fApi.Transfer.V1\xca\x02\x0fApi\\Transfer\\V1\xe2\x02\x1bApi\\Transfer\\V1\\GPBMetadata\xea\x02\x11Api::Transfer::V1b\x06proto3"

var file_api_transfer_v1_transfer_service_proto_goTypes = []any{
	(*TransferRequest)(nil),  // 0: api.transfer.v1.TransferRequest
	(*TransferResponse)(nil), // 1: api.transfer.v1.TransferResponse
}
var file_api_transfer_v1_transfer_service_proto_depIdxs = []int32{
	0, // 0: api.transfer.v1.TransferService.Transfer:input_type -> api.transfer.v1.TransferRequest
	1, // 1: api.transfer.v1.TransferService.Transfer:output_type -> api.transfer.v1.TransferResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_transfer_v1_transfer_service_proto_init() }
func file_api_transfer_v1_transfer_service_proto_init() {
	if File_api_transfer_v1_transfer_service_proto != nil {
		return
	}
	file_api_transfer_v1_transfer_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_transfer_v1_transfer_service_proto_rawDesc), len(file_api_transfer_v1_transfer_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_transfer_v1_transfer_service_proto_goTypes,
		DependencyIndexes: file_api_transfer_v1_transfer_service_proto_depIdxs,
	}.Build()
	File_api_transfer_v1_transfer_service_proto = out.File
	file_api_transfer_v1_transfer_service_proto_goTypes = nil
	file_api_transfer_v1_transfer_service_proto_depIdxs = nil
}
