// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"time"
)

type Transfer struct {
	ID        int64
	From      string
	To        string
	Amount    int64
	Currency  string
	CreatedAt time.Time
}
