// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"time"
)

type Bank struct {
	ID         int64
	Bid        string
	Code       string
	Name       string
	CountryID  int64
	CurrencyID int64
}

type Country struct {
	ID   int64
	Code string
	Name string
}

type Currency struct {
	ID        int64
	Code      string
	Name      string
	MinorUnit int64
}

type Destination struct {
	ID         int64
	Bid        string
	Code       string
	Name       string
	CountryID  int64
	CurrencyID int64
}

type Origin struct {
	ID         int64
	Bid        string
	Code       string
	Name       string
	CountryID  int64
	CurrencyID int64
}

type Transaction struct {
	ID            int64
	Tid           string
	OriginID      int64
	DestinationID int64
	CurrencyID    int64
	Amount        int64
	Status        string
	Reason        string
	CreatedAt     time.Time
}
