// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: query.sql

package db

import (
	"context"
)

const createBank = `-- name: CreateBank :one
INSERT INTO banks (
  code, name, country_id, currency_id
) VALUES (
  ?, ?, ?, ?
)
RETURNING id, code, name, country_id, currency_id
`

type CreateBankParams struct {
	Code       string
	Name       string
	CountryID  int64
	CurrencyID int64
}

func (q *Queries) CreateBank(ctx context.Context, arg CreateBankParams) (Bank, error) {
	row := q.db.QueryRowContext(ctx, createBank,
		arg.Code,
		arg.Name,
		arg.CountryID,
		arg.CurrencyID,
	)
	var i Bank
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.CountryID,
		&i.CurrencyID,
	)
	return i, err
}

const createCountry = `-- name: CreateCountry :exec
INSERT INTO countries (
  code, name
) VALUES (
  ?, ?
)
`

type CreateCountryParams struct {
	Code string
	Name string
}

func (q *Queries) CreateCountry(ctx context.Context, arg CreateCountryParams) error {
	_, err := q.db.ExecContext(ctx, createCountry, arg.Code, arg.Name)
	return err
}

const createCurrency = `-- name: CreateCurrency :exec
INSERT INTO currencies (
  code, name, minor_unit
) VALUES (
  ?, ?, ?
)
`

type CreateCurrencyParams struct {
	Code      string
	Name      string
	MinorUnit int64
}

func (q *Queries) CreateCurrency(ctx context.Context, arg CreateCurrencyParams) error {
	_, err := q.db.ExecContext(ctx, createCurrency, arg.Code, arg.Name, arg.MinorUnit)
	return err
}

const createTransaction = `-- name: CreateTransaction :one

INSERT INTO transactions (
  tid, origin_id, destination_id, currency_id, amount, status, reason
) VALUES (
  ?, ?, ?, ?, ?, ?, ?
)
RETURNING id, tid, origin_id, destination_id, currency_id, amount, status, reason, created_at
`

type CreateTransactionParams struct {
	Tid           string
	OriginID      int64
	DestinationID int64
	CurrencyID    int64
	Amount        int64
	Status        string
	Reason        string
}

// Transaction queries
func (q *Queries) CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error) {
	row := q.db.QueryRowContext(ctx, createTransaction,
		arg.Tid,
		arg.OriginID,
		arg.DestinationID,
		arg.CurrencyID,
		arg.Amount,
		arg.Status,
		arg.Reason,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.Tid,
		&i.OriginID,
		&i.DestinationID,
		&i.CurrencyID,
		&i.Amount,
		&i.Status,
		&i.Reason,
		&i.CreatedAt,
	)
	return i, err
}

const currencyExists = `-- name: CurrencyExists :one
SELECT
    EXISTS (
        SELECT
            1
        FROM
            currencies
        where
            code = ?
    )
`

func (q *Queries) CurrencyExists(ctx context.Context, code string) (int64, error) {
	row := q.db.QueryRowContext(ctx, currencyExists, code)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const deleteBankByCode = `-- name: DeleteBankByCode :exec
DELETE FROM banks WHERE code = ?
`

func (q *Queries) DeleteBankByCode(ctx context.Context, code string) error {
	_, err := q.db.ExecContext(ctx, deleteBankByCode, code)
	return err
}

const getBankByCode = `-- name: GetBankByCode :one

SELECT banks.id, banks.code, banks.name, banks.country_id, banks.currency_id, countries.id, countries.code, countries.name, currencies.id, currencies.code, currencies.name, currencies.minor_unit
FROM banks
JOIN countries on countries.id = banks.country_id
JOIN currencies on currencies.id = banks.currency_id
WHERE banks.code = ? LIMIT 1
`

type GetBankByCodeRow struct {
	Bank     Bank
	Country  Country
	Currency Currency
}

// Bank queries
func (q *Queries) GetBankByCode(ctx context.Context, code string) (GetBankByCodeRow, error) {
	row := q.db.QueryRowContext(ctx, getBankByCode, code)
	var i GetBankByCodeRow
	err := row.Scan(
		&i.Bank.ID,
		&i.Bank.Code,
		&i.Bank.Name,
		&i.Bank.CountryID,
		&i.Bank.CurrencyID,
		&i.Country.ID,
		&i.Country.Code,
		&i.Country.Name,
		&i.Currency.ID,
		&i.Currency.Code,
		&i.Currency.Name,
		&i.Currency.MinorUnit,
	)
	return i, err
}

const getCountryByCode = `-- name: GetCountryByCode :one

SELECT id, code, name FROM countries
WHERE code = ? LIMIT 1
`

// Country queries
func (q *Queries) GetCountryByCode(ctx context.Context, code string) (Country, error) {
	row := q.db.QueryRowContext(ctx, getCountryByCode, code)
	var i Country
	err := row.Scan(&i.ID, &i.Code, &i.Name)
	return i, err
}

const getCountryById = `-- name: GetCountryById :one
SELECT id, code, name FROM countries
WHERE id = ? LIMIT 1
`

func (q *Queries) GetCountryById(ctx context.Context, id int64) (Country, error) {
	row := q.db.QueryRowContext(ctx, getCountryById, id)
	var i Country
	err := row.Scan(&i.ID, &i.Code, &i.Name)
	return i, err
}

const getCurrencyByCode = `-- name: GetCurrencyByCode :one

SELECT id, code, name, minor_unit FROM currencies
WHERE code = ? LIMIT 1
`

// Currency queries
func (q *Queries) GetCurrencyByCode(ctx context.Context, code string) (Currency, error) {
	row := q.db.QueryRowContext(ctx, getCurrencyByCode, code)
	var i Currency
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.MinorUnit,
	)
	return i, err
}

const getCurrencyById = `-- name: GetCurrencyById :one
SELECT id, code, name, minor_unit FROM currencies
WHERE id = ? LIMIT 1
`

func (q *Queries) GetCurrencyById(ctx context.Context, id int64) (Currency, error) {
	row := q.db.QueryRowContext(ctx, getCurrencyById, id)
	var i Currency
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.MinorUnit,
	)
	return i, err
}

const listBanks = `-- name: ListBanks :many
SELECT id, code, name, country_id, currency_id FROM banks
LIMIT 50
`

func (q *Queries) ListBanks(ctx context.Context) ([]Bank, error) {
	rows, err := q.db.QueryContext(ctx, listBanks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Bank
	for rows.Next() {
		var i Bank
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.CountryID,
			&i.CurrencyID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBanksWithCountriesAndCurrencies = `-- name: ListBanksWithCountriesAndCurrencies :many
SELECT banks.id, banks.code, banks.name, banks.country_id, banks.currency_id, countries.id, countries.code, countries.name, currencies.id, currencies.code, currencies.name, currencies.minor_unit
FROM banks
JOIN countries ON countries.id = banks.country_id
JOIN currencies ON currencies.id = banks.currency_id
`

type ListBanksWithCountriesAndCurrenciesRow struct {
	Bank     Bank
	Country  Country
	Currency Currency
}

func (q *Queries) ListBanksWithCountriesAndCurrencies(ctx context.Context) ([]ListBanksWithCountriesAndCurrenciesRow, error) {
	rows, err := q.db.QueryContext(ctx, listBanksWithCountriesAndCurrencies)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListBanksWithCountriesAndCurrenciesRow
	for rows.Next() {
		var i ListBanksWithCountriesAndCurrenciesRow
		if err := rows.Scan(
			&i.Bank.ID,
			&i.Bank.Code,
			&i.Bank.Name,
			&i.Bank.CountryID,
			&i.Bank.CurrencyID,
			&i.Country.ID,
			&i.Country.Code,
			&i.Country.Name,
			&i.Currency.ID,
			&i.Currency.Code,
			&i.Currency.Name,
			&i.Currency.MinorUnit,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTransactions = `-- name: ListTransactions :many
SELECT
  transactions.id, transactions.tid, transactions.origin_id, transactions.destination_id, transactions.currency_id, transactions.amount, transactions.status, transactions.reason, transactions.created_at,
  origin.id, origin.code, origin.name, origin.country_id, origin.currency_id,
  destination.id, destination.code, destination.name, destination.country_id, destination.currency_id,
  currencies.id, currencies.code, currencies.name, currencies.minor_unit
FROM
  transactions
  JOIN banks AS origin ON origin.id = transactions.destination_id
  JOIN banks AS destination ON destination.id = transactions.origin_id
  JOIN currencies ON currencies.id = transactions.currency_id
ORDER BY
  created_at
`

type ListTransactionsRow struct {
	Transaction Transaction
	Bank        Bank
	Bank_2      Bank
	Currency    Currency
}

func (q *Queries) ListTransactions(ctx context.Context) ([]ListTransactionsRow, error) {
	rows, err := q.db.QueryContext(ctx, listTransactions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTransactionsRow
	for rows.Next() {
		var i ListTransactionsRow
		if err := rows.Scan(
			&i.Transaction.ID,
			&i.Transaction.Tid,
			&i.Transaction.OriginID,
			&i.Transaction.DestinationID,
			&i.Transaction.CurrencyID,
			&i.Transaction.Amount,
			&i.Transaction.Status,
			&i.Transaction.Reason,
			&i.Transaction.CreatedAt,
			&i.Bank.ID,
			&i.Bank.Code,
			&i.Bank.Name,
			&i.Bank.CountryID,
			&i.Bank.CurrencyID,
			&i.Bank_2.ID,
			&i.Bank_2.Code,
			&i.Bank_2.Name,
			&i.Bank_2.CountryID,
			&i.Bank_2.CurrencyID,
			&i.Currency.ID,
			&i.Currency.Code,
			&i.Currency.Name,
			&i.Currency.MinorUnit,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
