// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: proto/ledger/onboard/v1/bank.proto

package onboardv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetBankRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBankRequest) Reset() {
	*x = GetBankRequest{}
	mi := &file_proto_ledger_onboard_v1_bank_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBankRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBankRequest) ProtoMessage() {}

func (x *GetBankRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ledger_onboard_v1_bank_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBankRequest.ProtoReflect.Descriptor instead.
func (*GetBankRequest) Descriptor() ([]byte, []int) {
	return file_proto_ledger_onboard_v1_bank_proto_rawDescGZIP(), []int{0}
}

type GetBankResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBankResponse) Reset() {
	*x = GetBankResponse{}
	mi := &file_proto_ledger_onboard_v1_bank_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBankResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBankResponse) ProtoMessage() {}

func (x *GetBankResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ledger_onboard_v1_bank_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBankResponse.ProtoReflect.Descriptor instead.
func (*GetBankResponse) Descriptor() ([]byte, []int) {
	return file_proto_ledger_onboard_v1_bank_proto_rawDescGZIP(), []int{1}
}

type ListBanksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBanksRequest) Reset() {
	*x = ListBanksRequest{}
	mi := &file_proto_ledger_onboard_v1_bank_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBanksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBanksRequest) ProtoMessage() {}

func (x *ListBanksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ledger_onboard_v1_bank_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBanksRequest.ProtoReflect.Descriptor instead.
func (*ListBanksRequest) Descriptor() ([]byte, []int) {
	return file_proto_ledger_onboard_v1_bank_proto_rawDescGZIP(), []int{2}
}

type ListBanksResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBanksResponse) Reset() {
	*x = ListBanksResponse{}
	mi := &file_proto_ledger_onboard_v1_bank_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBanksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBanksResponse) ProtoMessage() {}

func (x *ListBanksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ledger_onboard_v1_bank_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBanksResponse.ProtoReflect.Descriptor instead.
func (*ListBanksResponse) Descriptor() ([]byte, []int) {
	return file_proto_ledger_onboard_v1_bank_proto_rawDescGZIP(), []int{3}
}

type CreateBankRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateBankRequest) Reset() {
	*x = CreateBankRequest{}
	mi := &file_proto_ledger_onboard_v1_bank_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBankRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBankRequest) ProtoMessage() {}

func (x *CreateBankRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ledger_onboard_v1_bank_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBankRequest.ProtoReflect.Descriptor instead.
func (*CreateBankRequest) Descriptor() ([]byte, []int) {
	return file_proto_ledger_onboard_v1_bank_proto_rawDescGZIP(), []int{4}
}

type CreateBankResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateBankResponse) Reset() {
	*x = CreateBankResponse{}
	mi := &file_proto_ledger_onboard_v1_bank_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBankResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBankResponse) ProtoMessage() {}

func (x *CreateBankResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ledger_onboard_v1_bank_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBankResponse.ProtoReflect.Descriptor instead.
func (*CreateBankResponse) Descriptor() ([]byte, []int) {
	return file_proto_ledger_onboard_v1_bank_proto_rawDescGZIP(), []int{5}
}

type DeleteBankRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteBankRequest) Reset() {
	*x = DeleteBankRequest{}
	mi := &file_proto_ledger_onboard_v1_bank_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteBankRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteBankRequest) ProtoMessage() {}

func (x *DeleteBankRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ledger_onboard_v1_bank_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteBankRequest.ProtoReflect.Descriptor instead.
func (*DeleteBankRequest) Descriptor() ([]byte, []int) {
	return file_proto_ledger_onboard_v1_bank_proto_rawDescGZIP(), []int{6}
}

type DeleteBankResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteBankResponse) Reset() {
	*x = DeleteBankResponse{}
	mi := &file_proto_ledger_onboard_v1_bank_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteBankResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteBankResponse) ProtoMessage() {}

func (x *DeleteBankResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ledger_onboard_v1_bank_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteBankResponse.ProtoReflect.Descriptor instead.
func (*DeleteBankResponse) Descriptor() ([]byte, []int) {
	return file_proto_ledger_onboard_v1_bank_proto_rawDescGZIP(), []int{7}
}

var File_proto_ledger_onboard_v1_bank_proto protoreflect.FileDescriptor

const file_proto_ledger_onboard_v1_bank_proto_rawDesc = "" +
	"\n" +
	"\"proto/ledger/onboard/v1/bank.proto\x12\x17proto.ledger.onboard.v1\"\x10\n" +
	"\x0eGetBankRequest\"\x11\n" +
	"\x0fGetBankResponse\"\x12\n" +
	"\x10ListBanksRequest\"\x13\n" +
	"\x11ListBanksResponse\"\x13\n" +
	"\x11CreateBankRequest\"\x14\n" +
	"\x12CreateBankResponse\"\x13\n" +
	"\x11DeleteBankRequest\"\x14\n" +
	"\x12DeleteBankResponseB\xe7\x01\n" +
	"\x1bcom.proto.ledger.onboard.v1B\tBankProtoP\x01Z>github.com/cosmonic-labs/wasmpay/ledger/internal/rpc/onboardv1\xa2\x02\x03PLO\xaa\x02\x17Proto.Ledger.Onboard.V1\xca\x02\x17Proto\\Ledger\\Onboard\\V1\xe2\x02#Proto\\Ledger\\Onboard\\V1\\GPBMetadata\xea\x02\x1aProto::Ledger::Onboard::V1b\x06proto3"

var (
	file_proto_ledger_onboard_v1_bank_proto_rawDescOnce sync.Once
	file_proto_ledger_onboard_v1_bank_proto_rawDescData []byte
)

func file_proto_ledger_onboard_v1_bank_proto_rawDescGZIP() []byte {
	file_proto_ledger_onboard_v1_bank_proto_rawDescOnce.Do(func() {
		file_proto_ledger_onboard_v1_bank_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_ledger_onboard_v1_bank_proto_rawDesc), len(file_proto_ledger_onboard_v1_bank_proto_rawDesc)))
	})
	return file_proto_ledger_onboard_v1_bank_proto_rawDescData
}

var file_proto_ledger_onboard_v1_bank_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_proto_ledger_onboard_v1_bank_proto_goTypes = []any{
	(*GetBankRequest)(nil),     // 0: proto.ledger.onboard.v1.GetBankRequest
	(*GetBankResponse)(nil),    // 1: proto.ledger.onboard.v1.GetBankResponse
	(*ListBanksRequest)(nil),   // 2: proto.ledger.onboard.v1.ListBanksRequest
	(*ListBanksResponse)(nil),  // 3: proto.ledger.onboard.v1.ListBanksResponse
	(*CreateBankRequest)(nil),  // 4: proto.ledger.onboard.v1.CreateBankRequest
	(*CreateBankResponse)(nil), // 5: proto.ledger.onboard.v1.CreateBankResponse
	(*DeleteBankRequest)(nil),  // 6: proto.ledger.onboard.v1.DeleteBankRequest
	(*DeleteBankResponse)(nil), // 7: proto.ledger.onboard.v1.DeleteBankResponse
}
var file_proto_ledger_onboard_v1_bank_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_ledger_onboard_v1_bank_proto_init() }
func file_proto_ledger_onboard_v1_bank_proto_init() {
	if File_proto_ledger_onboard_v1_bank_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_ledger_onboard_v1_bank_proto_rawDesc), len(file_proto_ledger_onboard_v1_bank_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_ledger_onboard_v1_bank_proto_goTypes,
		DependencyIndexes: file_proto_ledger_onboard_v1_bank_proto_depIdxs,
		MessageInfos:      file_proto_ledger_onboard_v1_bank_proto_msgTypes,
	}.Build()
	File_proto_ledger_onboard_v1_bank_proto = out.File
	file_proto_ledger_onboard_v1_bank_proto_goTypes = nil
	file_proto_ledger_onboard_v1_bank_proto_depIdxs = nil
}
