// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: proto/ledger/onboard/v1/onboard_service.proto

package onboardv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_proto_ledger_onboard_v1_onboard_service_proto protoreflect.FileDescriptor

const file_proto_ledger_onboard_v1_onboard_service_proto_rawDesc = "" +
	"\n" +
	"-proto/ledger/onboard/v1/onboard_service.proto\x12\x17proto.ledger.onboard.v1\x1a\"proto/ledger/onboard/v1/bank.proto\x1a&proto/ledger/onboard/v1/customer.proto2\xf0\x06\n" +
	"\x0eOnboardService\x12^\n" +
	"\aGetBank\x12'.proto.ledger.onboard.v1.GetBankRequest\x1a(.proto.ledger.onboard.v1.GetBankResponse\"\x00\x12d\n" +
	"\tListBanks\x12).proto.ledger.onboard.v1.ListBanksRequest\x1a*.proto.ledger.onboard.v1.ListBanksResponse\"\x00\x12g\n" +
	"\n" +
	"CreateBank\x12*.proto.ledger.onboard.v1.CreateBankRequest\x1a+.proto.ledger.onboard.v1.CreateBankResponse\"\x00\x12g\n" +
	"\n" +
	"DeleteBank\x12*.proto.ledger.onboard.v1.DeleteBankRequest\x1a+.proto.ledger.onboard.v1.DeleteBankResponse\"\x00\x12j\n" +
	"\vGetCustomer\x12+.proto.ledger.onboard.v1.GetCustomerRequest\x1a,.proto.ledger.onboard.v1.GetCustomerResponse\"\x00\x12p\n" +
	"\rListCustomers\x12-.proto.ledger.onboard.v1.ListCustomersRequest\x1a..proto.ledger.onboard.v1.ListCustomersResponse\"\x00\x12s\n" +
	"\x0eCreateCustomer\x12..proto.ledger.onboard.v1.CreateCustomerRequest\x1a/.proto.ledger.onboard.v1.CreateCustomerResponse\"\x00\x12s\n" +
	"\x0eDeleteCustomer\x12..proto.ledger.onboard.v1.DeleteCustomerRequest\x1a/.proto.ledger.onboard.v1.DeleteCustomerResponse\"\x00B\xf1\x01\n" +
	"\x1bcom.proto.ledger.onboard.v1B\x13OnboardServiceProtoP\x01Z>github.com/cosmonic-labs/wasmpay/ledger/internal/rpc/onboardv1\xa2\x02\x03PLO\xaa\x02\x17Proto.Ledger.Onboard.V1\xca\x02\x17Proto\\Ledger\\Onboard\\V1\xe2\x02#Proto\\Ledger\\Onboard\\V1\\GPBMetadata\xea\x02\x1aProto::Ledger::Onboard::V1b\x06proto3"

var file_proto_ledger_onboard_v1_onboard_service_proto_goTypes = []any{
	(*GetBankRequest)(nil),         // 0: proto.ledger.onboard.v1.GetBankRequest
	(*ListBanksRequest)(nil),       // 1: proto.ledger.onboard.v1.ListBanksRequest
	(*CreateBankRequest)(nil),      // 2: proto.ledger.onboard.v1.CreateBankRequest
	(*DeleteBankRequest)(nil),      // 3: proto.ledger.onboard.v1.DeleteBankRequest
	(*GetCustomerRequest)(nil),     // 4: proto.ledger.onboard.v1.GetCustomerRequest
	(*ListCustomersRequest)(nil),   // 5: proto.ledger.onboard.v1.ListCustomersRequest
	(*CreateCustomerRequest)(nil),  // 6: proto.ledger.onboard.v1.CreateCustomerRequest
	(*DeleteCustomerRequest)(nil),  // 7: proto.ledger.onboard.v1.DeleteCustomerRequest
	(*GetBankResponse)(nil),        // 8: proto.ledger.onboard.v1.GetBankResponse
	(*ListBanksResponse)(nil),      // 9: proto.ledger.onboard.v1.ListBanksResponse
	(*CreateBankResponse)(nil),     // 10: proto.ledger.onboard.v1.CreateBankResponse
	(*DeleteBankResponse)(nil),     // 11: proto.ledger.onboard.v1.DeleteBankResponse
	(*GetCustomerResponse)(nil),    // 12: proto.ledger.onboard.v1.GetCustomerResponse
	(*ListCustomersResponse)(nil),  // 13: proto.ledger.onboard.v1.ListCustomersResponse
	(*CreateCustomerResponse)(nil), // 14: proto.ledger.onboard.v1.CreateCustomerResponse
	(*DeleteCustomerResponse)(nil), // 15: proto.ledger.onboard.v1.DeleteCustomerResponse
}
var file_proto_ledger_onboard_v1_onboard_service_proto_depIdxs = []int32{
	0,  // 0: proto.ledger.onboard.v1.OnboardService.GetBank:input_type -> proto.ledger.onboard.v1.GetBankRequest
	1,  // 1: proto.ledger.onboard.v1.OnboardService.ListBanks:input_type -> proto.ledger.onboard.v1.ListBanksRequest
	2,  // 2: proto.ledger.onboard.v1.OnboardService.CreateBank:input_type -> proto.ledger.onboard.v1.CreateBankRequest
	3,  // 3: proto.ledger.onboard.v1.OnboardService.DeleteBank:input_type -> proto.ledger.onboard.v1.DeleteBankRequest
	4,  // 4: proto.ledger.onboard.v1.OnboardService.GetCustomer:input_type -> proto.ledger.onboard.v1.GetCustomerRequest
	5,  // 5: proto.ledger.onboard.v1.OnboardService.ListCustomers:input_type -> proto.ledger.onboard.v1.ListCustomersRequest
	6,  // 6: proto.ledger.onboard.v1.OnboardService.CreateCustomer:input_type -> proto.ledger.onboard.v1.CreateCustomerRequest
	7,  // 7: proto.ledger.onboard.v1.OnboardService.DeleteCustomer:input_type -> proto.ledger.onboard.v1.DeleteCustomerRequest
	8,  // 8: proto.ledger.onboard.v1.OnboardService.GetBank:output_type -> proto.ledger.onboard.v1.GetBankResponse
	9,  // 9: proto.ledger.onboard.v1.OnboardService.ListBanks:output_type -> proto.ledger.onboard.v1.ListBanksResponse
	10, // 10: proto.ledger.onboard.v1.OnboardService.CreateBank:output_type -> proto.ledger.onboard.v1.CreateBankResponse
	11, // 11: proto.ledger.onboard.v1.OnboardService.DeleteBank:output_type -> proto.ledger.onboard.v1.DeleteBankResponse
	12, // 12: proto.ledger.onboard.v1.OnboardService.GetCustomer:output_type -> proto.ledger.onboard.v1.GetCustomerResponse
	13, // 13: proto.ledger.onboard.v1.OnboardService.ListCustomers:output_type -> proto.ledger.onboard.v1.ListCustomersResponse
	14, // 14: proto.ledger.onboard.v1.OnboardService.CreateCustomer:output_type -> proto.ledger.onboard.v1.CreateCustomerResponse
	15, // 15: proto.ledger.onboard.v1.OnboardService.DeleteCustomer:output_type -> proto.ledger.onboard.v1.DeleteCustomerResponse
	8,  // [8:16] is the sub-list for method output_type
	0,  // [0:8] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_proto_ledger_onboard_v1_onboard_service_proto_init() }
func file_proto_ledger_onboard_v1_onboard_service_proto_init() {
	if File_proto_ledger_onboard_v1_onboard_service_proto != nil {
		return
	}
	file_proto_ledger_onboard_v1_bank_proto_init()
	file_proto_ledger_onboard_v1_customer_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_ledger_onboard_v1_onboard_service_proto_rawDesc), len(file_proto_ledger_onboard_v1_onboard_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_ledger_onboard_v1_onboard_service_proto_goTypes,
		DependencyIndexes: file_proto_ledger_onboard_v1_onboard_service_proto_depIdxs,
	}.Build()
	File_proto_ledger_onboard_v1_onboard_service_proto = out.File
	file_proto_ledger_onboard_v1_onboard_service_proto_goTypes = nil
	file_proto_ledger_onboard_v1_onboard_service_proto_depIdxs = nil
}
