// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: proto/ledger/v1/ledger.proto

package ledgerv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TransferRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// What account is sending money
	From string `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	// What account is money being sent to
	To string `protobuf:"bytes,2,opt,name=to,proto3" json:"to,omitempty"`
	// Currency-appropriate denomination
	Amount uint32 `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
	// Currency
	Currency      string `protobuf:"bytes,4,opt,name=currency,proto3" json:"currency,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransferRequest) Reset() {
	*x = TransferRequest{}
	mi := &file_proto_ledger_v1_ledger_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransferRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferRequest) ProtoMessage() {}

func (x *TransferRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ledger_v1_ledger_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferRequest.ProtoReflect.Descriptor instead.
func (*TransferRequest) Descriptor() ([]byte, []int) {
	return file_proto_ledger_v1_ledger_proto_rawDescGZIP(), []int{0}
}

func (x *TransferRequest) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *TransferRequest) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *TransferRequest) GetAmount() uint32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *TransferRequest) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

type TransferResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransferResponse) Reset() {
	*x = TransferResponse{}
	mi := &file_proto_ledger_v1_ledger_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransferResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferResponse) ProtoMessage() {}

func (x *TransferResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ledger_v1_ledger_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferResponse.ProtoReflect.Descriptor instead.
func (*TransferResponse) Descriptor() ([]byte, []int) {
	return file_proto_ledger_v1_ledger_proto_rawDescGZIP(), []int{1}
}

func (x *TransferResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_proto_ledger_v1_ledger_proto protoreflect.FileDescriptor

const file_proto_ledger_v1_ledger_proto_rawDesc = "" +
	"\n" +
	"\x1cproto/ledger/v1/ledger.proto\x12\tledger.v1\"i\n" +
	"\x0fTransferRequest\x12\x12\n" +
	"\x04from\x18\x01 \x01(\tR\x04from\x12\x0e\n" +
	"\x02to\x18\x02 \x01(\tR\x02to\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\rR\x06amount\x12\x1a\n" +
	"\bcurrency\x18\x04 \x01(\tR\bcurrency\",\n" +
	"\x10TransferResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2V\n" +
	"\rLedgerService\x12E\n" +
	"\bTransfer\x12\x1a.ledger.v1.TransferRequest\x1a\x1b.ledger.v1.TransferResponse\"\x00B\xa0\x01\n" +
	"\rcom.ledger.v1B\vLedgerProtoP\x01Z=github.com/cosmonic-labs/wasmpay/ledger/internal/rpc/ledgerv1\xa2\x02\x03LXX\xaa\x02\tLedger.V1\xca\x02\tLedger\\V1\xe2\x02\x15Ledger\\V1\\GPBMetadata\xea\x02\n" +
	"Ledger::V1b\x06proto3"

var (
	file_proto_ledger_v1_ledger_proto_rawDescOnce sync.Once
	file_proto_ledger_v1_ledger_proto_rawDescData []byte
)

func file_proto_ledger_v1_ledger_proto_rawDescGZIP() []byte {
	file_proto_ledger_v1_ledger_proto_rawDescOnce.Do(func() {
		file_proto_ledger_v1_ledger_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_ledger_v1_ledger_proto_rawDesc), len(file_proto_ledger_v1_ledger_proto_rawDesc)))
	})
	return file_proto_ledger_v1_ledger_proto_rawDescData
}

var file_proto_ledger_v1_ledger_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_ledger_v1_ledger_proto_goTypes = []any{
	(*TransferRequest)(nil),  // 0: ledger.v1.TransferRequest
	(*TransferResponse)(nil), // 1: ledger.v1.TransferResponse
}
var file_proto_ledger_v1_ledger_proto_depIdxs = []int32{
	0, // 0: ledger.v1.LedgerService.Transfer:input_type -> ledger.v1.TransferRequest
	1, // 1: ledger.v1.LedgerService.Transfer:output_type -> ledger.v1.TransferResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_ledger_v1_ledger_proto_init() }
func file_proto_ledger_v1_ledger_proto_init() {
	if File_proto_ledger_v1_ledger_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_ledger_v1_ledger_proto_rawDesc), len(file_proto_ledger_v1_ledger_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_ledger_v1_ledger_proto_goTypes,
		DependencyIndexes: file_proto_ledger_v1_ledger_proto_depIdxs,
		MessageInfos:      file_proto_ledger_v1_ledger_proto_msgTypes,
	}.Build()
	File_proto_ledger_v1_ledger_proto = out.File
	file_proto_ledger_v1_ledger_proto_goTypes = nil
	file_proto_ledger_v1_ledger_proto_depIdxs = nil
}
