// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: api/transaction/v1/transaction_service.proto

package transactionv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	transactionv1 "github.com/cosmonic-labs/wasmpay/ledger/internal/api/transactionv1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// TransactionServiceName is the fully-qualified name of the TransactionService service.
	TransactionServiceName = "api.transaction.v1.TransactionService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// TransactionServiceTransactionProcedure is the fully-qualified name of the TransactionService's
	// Transaction RPC.
	TransactionServiceTransactionProcedure = "/api.transaction.v1.TransactionService/Transaction"
)

// TransactionServiceClient is a client for the api.transaction.v1.TransactionService service.
type TransactionServiceClient interface {
	Transaction(context.Context, *connect.Request[transactionv1.TransactionRequest]) (*connect.Response[transactionv1.TransactionResponse], error)
}

// NewTransactionServiceClient constructs a client for the api.transaction.v1.TransactionService
// service. By default, it uses the Connect protocol with the binary Protobuf Codec, asks for
// gzipped responses, and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply
// the connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewTransactionServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) TransactionServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	transactionServiceMethods := transactionv1.File_api_transaction_v1_transaction_service_proto.Services().ByName("TransactionService").Methods()
	return &transactionServiceClient{
		transaction: connect.NewClient[transactionv1.TransactionRequest, transactionv1.TransactionResponse](
			httpClient,
			baseURL+TransactionServiceTransactionProcedure,
			connect.WithSchema(transactionServiceMethods.ByName("Transaction")),
			connect.WithClientOptions(opts...),
		),
	}
}

// transactionServiceClient implements TransactionServiceClient.
type transactionServiceClient struct {
	transaction *connect.Client[transactionv1.TransactionRequest, transactionv1.TransactionResponse]
}

// Transaction calls api.transaction.v1.TransactionService.Transaction.
func (c *transactionServiceClient) Transaction(ctx context.Context, req *connect.Request[transactionv1.TransactionRequest]) (*connect.Response[transactionv1.TransactionResponse], error) {
	return c.transaction.CallUnary(ctx, req)
}

// TransactionServiceHandler is an implementation of the api.transaction.v1.TransactionService
// service.
type TransactionServiceHandler interface {
	Transaction(context.Context, *connect.Request[transactionv1.TransactionRequest]) (*connect.Response[transactionv1.TransactionResponse], error)
}

// NewTransactionServiceHandler builds an HTTP handler from the service implementation. It returns
// the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewTransactionServiceHandler(svc TransactionServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	transactionServiceMethods := transactionv1.File_api_transaction_v1_transaction_service_proto.Services().ByName("TransactionService").Methods()
	transactionServiceTransactionHandler := connect.NewUnaryHandler(
		TransactionServiceTransactionProcedure,
		svc.Transaction,
		connect.WithSchema(transactionServiceMethods.ByName("Transaction")),
		connect.WithHandlerOptions(opts...),
	)
	return "/api.transaction.v1.TransactionService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case TransactionServiceTransactionProcedure:
			transactionServiceTransactionHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedTransactionServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedTransactionServiceHandler struct{}

func (UnimplementedTransactionServiceHandler) Transaction(context.Context, *connect.Request[transactionv1.TransactionRequest]) (*connect.Response[transactionv1.TransactionResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("api.transaction.v1.TransactionService.Transaction is not implemented"))
}
