name = "transaction-manager"
version = "0.1.0"
language = "rust"
type = "component"
wit = "../wit"

[component]
wit_world = "transaction-manager"
# build_command = "./build.sh"
# build_artifact = "build/transaction-manager.composed.wasm"
wasm_target = "wasm32-wasip2"
