name: "wash: Setup"
description: This action installs wash and necessary web assembly tools for Rust & Go projects
inputs:
  go-version-file:
    description: "Path to go.work or go.mod file"
    required: false
  go-cache-dependency-path:
    description: "Path to go.sum file for dependency caching"
    required: false
  tinygo-version:
    description: "Tinygo version"
    required: false
    default: "0.36.0"
  wasm-tools-version:
    description: "Wasm-tools version"
    required: false
    default: "1.223.1"
  wash-version:
    description: "Wash version"
    required: false
    default: "0.40.0"
  rust-toolchain:
    description: "Rust toolchain"
    required: false
    default: "stable"
  rust-target:
    description: "Rust target"
    required: false
    default: "wasm32-wasip2"
  node-version:
    description: "Node version"
    required: false
    default: "18"

runs:
  using: "composite"
  steps:
    # Rust Setup
    - name: Install Rust
      uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        toolchain: ${{ inputs.rust-toolchain }}
        target: ${{ inputs.rust-target }}
    # Go Setup
    - name: Install Go
      uses: actions/setup-go@v5.2.0
      with:
        go-version-file: ${{ inputs.go-version-file }}
        cache-dependency-path: ${{ inputs.go-cache-dependency-path }}
    - name: Install tinygo
      uses: acifani/setup-tinygo@v2.0.0
      with:
        tinygo-version: ${{ inputs.tinygo-version }}
    # Node/Typescript Setup
    - uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
    # WASM Setup
    - name: Install wac-cli, wasm-tools, and wash
      uses: taiki-e/install-action@v2
      with:
        tool: wac-cli,wasm-tools@${{ inputs.wasm-tools-version }},wash@${{ inputs.wash-version }}
