name: docker / ollama

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/ollama.yml'
      - 'Dockerfile.ollama'
  pull_request:
    branches:
      - main
    paths:
      - '.github/workflows/ollama.yml'
      - 'Dockerfile.ollama'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: cosmonic-labs/demo/ollama
  IMAGE_TAG: '0.1.0'

jobs:
  build:
    runs-on: ubuntu-latest
    name: ${{ (github.event_name == 'push' && github.ref == 'refs/heads/main') && 'Build and Push' || 'Build' }}
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log into GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push the image
        uses: docker/build-push-action@v6
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        with:
          file: Dockerfile.ollama
          push: true
          context: .
          tags: ${{ env.REGISTRY}}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
          platforms: linux/amd64,linux/arm64
