name: "wash: Push Component"
description: This action pushes a component to an OCI registry using wash
inputs:
  registry-username:
    description: "OCI registry username"
    required: true
  registry-password:
    description: "OCI registry password"
    required: true
  image:
    description: "Image in the format of <registry>/<repository>:<tag>"
    required: true
  # NOTE(lxf): would be nice to get this straight from wasmcloud.toml or wash. but wash doesn't have a way to get the artifact name.
  artifact:
    description: "Artifact to push"
    required: true
  # Optionals
  working-directory:
    description: "Directory with wasmcloud.toml"
    default: "."
    required: false
  push-args:
    description: "wash push arguments"
    default: "--allow-latest"
    required: false
runs:
  using: "composite"
  steps:
    - name: Push Component
      shell: "bash"
      working-directory: "${{ inputs.working-directory }}"
      env:
        WASH_REG_USER: ${{ inputs.registry-username }}
        WASH_REG_PASSWORD: ${{ inputs.registry-password }}
      run: wash push ${{ inputs.push-args }} ${{ inputs.image }} ${{ inputs.artifact }}
