
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: dev-iudfhi-nordhaven-validator
  annotations:
    example: yarp
  labels:
    wasmcloud.dev/generated-by: wash-dev
spec:
  components:
  - name: nordhaven-validator
    type: component
    properties:
      image: ttl.sh/wasmcloud/nordhaven-validator:24h
      id: nordhaven-validator
    traits:
    - type: spreadscaler
      properties:
        instances: 100
    - type: link
      properties:
        namespace: wasmcloud
        package: messaging
        interfaces:
        - consumer
        target:
          name: dep-custom-wasmcloud-messaging-consumer
  - name: dep-custom-wasmcloud-messaging-handler
    type: capability
    properties:
      image: wasmcloud+builtin://messaging-nats
      config:
      - name: custom-wasmcloud-messaging-default
        properties:
          subscription: wasmcloud.dev
    traits:
    - type: link
      properties:
        namespace: wasmcloud
        package: messaging
        interfaces:
        - handler
        source:
          config:
          - name: wasmcloud-messaging-config
            properties:
              subscriptions: wasmcloud.dev
        target:
          name: nordhaven-validator
  - name: dep-custom-wasmcloud-messaging-consumer
    type: capability
    properties:
      image: wasmcloud+builtin://messaging-nats
      config:
      - name: custom-wasmcloud-messaging-default
        properties:
          subscription: wasmcloud.dev
    traits: []

