name: artifacts

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      # Checkout repository
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      # Environment Setup (Rust, Go, Node, WASM Tooling)
      - name: Setup WASM Build Environment
        uses: ./.github/actions/wash-setup
        with:
          # optional: specify go version file to use.
          go-version-file: go.work
          # optional: specify go cache dependency path to use.
          go-cache-dependency-path: '*/go.sum'
      
      # WAC/Donut: wasmpay-messaging
      # will be used by other components as dependency.
      - name: Build wasmpay-messaging
        uses: ./.github/actions/wash-build
        with:
          working-directory: wasmpay-messaging

      # Component: API Gateway
      # build static UI so it can be embedded in the wasm binary.
      - name: Build Banking UI
        working-directory: api-gateway/wasmcloud.banking
        run: |
          npm ci
          npm run build --workspaces --if-present
      
      - name: Build API Gateway
        uses: ./.github/actions/wash-build
        with:
          working-directory: api-gateway

      - name: Push API Gateway
        if: github.ref == 'refs/heads/main'
        uses: ./.github/actions/wash-push
        with:
          working-directory: api-gateway
          registry-username: ${{ github.actor }}
          registry-password: ${{ secrets.GITHUB_TOKEN }}
          artifact: build/api-gateway_s.wasm
          image: ghcr.io/cosmonic-labs/wasmpay/api-gateway:latest
    
      # Component: Transaction Manager
      - name: Build Transaction Manager
        uses: ./.github/actions/wash-build
        with:
          working-directory: transaction-manager

      # Component: icamer-validator
      - name: Build icamer-validator
        uses: ./.github/actions/wash-build
        with:
          working-directory: icamer-validator
      
      - name: Push icamer-validator
        if: github.ref == 'refs/heads/main'
        uses: ./.github/actions/wash-push
        with:
          working-directory: icamer-validator
          registry-username: ${{ github.actor }}
          registry-password: ${{ secrets.GITHUB_TOKEN }}
          artifact: build/icamer_validator.composed_s.wasm
          image: ghcr.io/cosmonic-labs/wasmpay/icamer-validator:latest